name: ci
on:
  pull_request:
  merge_group:
  push:
    branches:
      - "main"
      - "renovate/lock-file-maintenance"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci --omit=optional

      - name: Run linter
        run: npm run lint:ci

      - name: Install end-to-end tests dependencies
        run: npx playwright install --with-deps chromium

      - name: Run modules smoke tests
        run: npm run test:modules -- --ci --runInBand --testNamePattern='@smoke'

      - name: Run end-to-end smoke tests
        run: npm run test:e2e -- --grep='@smoke'

      - name: Run modules sanity tests
        run: npm run test:modules -- --ci --runInBand --testNamePattern='@sanity'

      - name: Run end-to-end sanity tests
        run: npm run test:e2e -- --grep='@sanity'

      - name: Run modules tests
        if: github.event_name == 'push' && (contains(github.ref, 'main') || contains(github.ref, 'renovate/lock-file-maintenance'))
        run: npm run test:modules -- --ci --runInBand --testNamePattern='^((?!@smoke|@sanity).)*$'

      - name: Run end-to-end tests
        if: github.event_name == 'push' && (contains(github.ref, 'main') || contains(github.ref, 'renovate/lock-file-maintenance'))
        run: npm run test:e2e -- --grep-invert='@smoke|@sanity'
